Indoor_app/Controllers/ModelControllers/beaconsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Indoor_app.Models;

namespace Indoor_app.Controllers
{
    [Authorize(Users = AccessLevelUsers.Users)]
    public class beaconsController : Controller
    {
        private BeaconDBEntities db = new BeaconDBEntities();

        // GET: beacons
        [AllowAnonymous]
        public ActionResult Index(string sortOrder)
        {
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.BatteryLevelSortParm = sortOrder == "batteryLevel" ? "batteryLevel_desc" : "batteryLevel";
            ViewBag.NodeIdSortParm = sortOrder == "nodeID" ? "nodeID_desc" : "nodeID";
            ViewBag.MapLevelSortParm = sortOrder == "mapLevel" ? "mapLevel_desc" : "mapLevel";
            ViewBag.BuildingSortParm = sortOrder == "building" ? "building_desc" : "building";

            var beacons = from s in db.beacons select s;
            switch (sortOrder)
            {
                case "batteryLevel":
                    beacons = beacons.OrderBy(s => s.batteryLevel);
                    break;
                case "batteryLevel_desc":
                    beacons = beacons.OrderByDescending(s => s.batteryLevel);
                    break;
                case "nodeID":
                    beacons = beacons.OrderBy(s => s.nodes.nodeID);
                    break;
                case "nodeID_desc":
                    beacons = beacons.OrderByDescending(s => s.nodes.nodeID);
                    break;
                case "mapLevel":
                    beacons = beacons.OrderBy(s => s.nodes.floors.mapLevel);
                    break;
                case "mapLevel_desc":
                    beacons = beacons.OrderByDescending(s => s.nodes.floors.mapLevel);
                    break;
                case "building":
                    beacons = beacons.OrderBy(s => s.nodes.floors.buildings.buildingName);
                    break;
                case "building_desc":
                    beacons = beacons.OrderByDescending(s => s.nodes.floors.buildings.buildingName);
                    break;
                case "id_desc":
                    beacons = beacons.OrderByDescending(s => s.beaconID);
                    break;
                default:
                    beacons = beacons.OrderBy(s => s.beaconID);
                    break;
            }
            return View(beacons.ToList());
            //var beacons = db.beacons.Include(b => b.nodes);
            //return View(beacons.ToList());
        }

        // GET: beacons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            beacons beacons = db.beacons.Find(id);
            if (beacons == null)
            {
                return HttpNotFound();
            }
            return View(beacons);
        }

        // GET: beacons/Create
        public ActionResult Create()
        {
            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID");
            return View();
        }

        // POST: beacons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "beaconID,title,uuid,minor,major,batteryLevel,language,nodeID")] beacons beacons)
        {
            if (ModelState.IsValid)
            {
                db.beacons.Add(beacons);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID", beacons.nodeID);
            return View(beacons);
        }

        // GET: beacons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            beacons beacons = db.beacons.Find(id);
            if (beacons == null)
            {
                return HttpNotFound();
            }
            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID", beacons.nodeID);
            return View(beacons);
        }

        // POST: beacons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "beaconID,title,uuid,minor,major,batteryLevel,language,nodeID")] beacons beacons)
        {
            if (ModelState.IsValid)
            {
                db.Entry(beacons).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID", beacons.nodeID);
            return View(beacons);
        }

        // GET: beacons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            beacons beacons = db.beacons.Find(id);
            if (beacons == null)
            {
                return HttpNotFound();
            }
            return View(beacons);
        }

        // POST: beacons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            beacons beacons = db.beacons.Find(id);
            db.beacons.Remove(beacons);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Indoor_app/Controllers/ModelControllers/nodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Indoor_app.Models;

namespace Indoor_app.Controllers
{
    [Authorize(Users = AccessLevelUsers.Users)]
    public class nodesController : Controller
    {
        private BeaconDBEntities db = new BeaconDBEntities();

        // GET: nodes
        [AllowAnonymous]
        public ActionResult Index(string sortOrder)
        {
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.RoomTypeSortParm = sortOrder == "roomType" ? "roomType_desc" : "roomType";
            ViewBag.RoomNumSortParm = sortOrder == "roomNum" ? "roomNum_desc" : "roomNum";
            ViewBag.TypeSortParm = sortOrder == "type" ? "type_desc" : "type";
            ViewBag.FloorIdSortParm = sortOrder == "floorID" ? "floorID_desc" : "floorID";
            ViewBag.MapLevelSortParm = sortOrder == "mapLevel" ? "mapLevel_desc" : "mapLevel";
            ViewBag.BuildingSortParm = sortOrder == "building" ? "building_desc" : "building";

            var nodes = from s in db.nodes select s;
            switch (sortOrder)
            {
                case "roomType":
                    nodes = nodes.OrderBy(s => s.roomType);
                    break;
                case "roomType_desc":
                    nodes = nodes.OrderByDescending(s => s.roomType);
                    break;
                case "roomNum":
                    nodes = nodes.OrderBy(s => s.roomNum);
                    break;
                case "roomNum_desc":
                    nodes = nodes.OrderByDescending(s => s.roomNum);
                    break;
                case "type":
                    nodes = nodes.OrderBy(s => s.type);
                    break;
                case "type_desc":
                    nodes = nodes.OrderByDescending(s => s.type);
                    break;
                case "floorID":
                    nodes = nodes.OrderBy(s => s.floors.floorID);
                    break;
                case "floorID_desc":
                    nodes = nodes.OrderByDescending(s => s.floors.floorID);
                    break;
                case "mapLevel":
                    nodes = nodes.OrderBy(s => s.floors.mapLevel);
                    break;
                case "mapLevel_desc":
                    nodes = nodes.OrderByDescending(s => s.floors.mapLevel);
                    break;
                case "building":
                    nodes = nodes.OrderBy(s => s.floors.buildings.buildingName);
                    break;
                case "building_desc":
                    nodes = nodes.OrderByDescending(s => s.floors.buildings.buildingName);
                    break;
                case "id_desc":
                    nodes = nodes.OrderByDescending(s => s.nodeID);
                    break;
                default:
                    nodes = nodes.OrderBy(s => s.nodeID);
                    break;
            }
            return View(nodes.ToList());

            //var nodes = db.nodes.Include(n => n.floors);
            //return View(nodes.ToList());
        }

        // GET: nodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nodes nodes = db.nodes.Find(id);
            if (nodes == null)
            {
                return HttpNotFound();
            }
            return View(nodes);
        }

        // GET: nodes/Create
        public ActionResult Create()
        {
            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID");
            return View();
        }

        // POST: nodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nodeID,description,roomType,roomNum,coordX,coordY,type,floorID")] nodes nodes)
        {
            if (ModelState.IsValid)
            {
                db.nodes.Add(nodes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID", nodes.floorID);
            return View(nodes);
        }

        // GET: nodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nodes nodes = db.nodes.Find(id);

            if (nodes == null)
            {
                return HttpNotFound();
            }
            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID", nodes.floorID);
            
            
            //ViewBag.buildingNameRUS = new SelectList(db.buildings, "buildingNameRU", "buildingNameRU", nodes.floors.buildings.buildingNameRu);
            return View(nodes);
        }

        // POST: nodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nodeID,description,roomType,roomNum,coordX,coordY,type,floorID")] nodes nodes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nodes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID", nodes.floorID);

            //мультиселект?
            //@Html.DropDownList("buildingNameRUS", null, htmlAttributes: new { @class = "form-control" })
            //ViewBag.buildingNameRUS = new SelectList(db.buildings, "floorID", "buildingNameRU", nodes.floors.buildings.buildingNameRu);

            return View(nodes);
        }

        // GET: nodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nodes nodes = db.nodes.Find(id);
            if (nodes == null)
            {
                return HttpNotFound();
            }
            return View(nodes);
        }

        // POST: nodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            nodes nodes = db.nodes.Find(id);
            db.nodes.Remove(nodes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Indoor_app/Views/beacons/Create.cshtml
@model Indoor_app.Models.beacons

@{
    ViewBag.Title = "Добавление бикона";
}

    <h2>Добавление</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uuid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uuid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uuid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.minor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.minor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.major, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.major, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.major, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.batteryLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.batteryLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.batteryLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nodeID, "ID ноды", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nodeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nodeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку биконов", "Index")
</div>

Indoor_app/Views/beacons/Delete.cshtml
@model Indoor_app.Models.beacons

@{
    ViewBag.Title = "Удаление бикона";
}

<h2>Удаление</h2>

<h3>Точно хотите удалить этот бикон?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.uuid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.uuid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.major)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.major)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.batteryLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.batteryLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nodes.nodeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nodes.nodeID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К списку биконов", "Index")
        </div>
    }
</div>

Indoor_app/Views/beacons/Details.cshtml
@model Indoor_app.Models.beacons

@{
    ViewBag.Title = "Описание бикона";
}

<h2>Описание</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.uuid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.uuid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.major)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.major)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.batteryLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.batteryLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.language)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nodes.nodeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nodes.nodeID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактирование", "Edit", new { id = Model.beaconID }) |
    @Html.ActionLink("К списку биконов", "Index")
</p>

Indoor_app/Views/beacons/Edit.cshtml
@model Indoor_app.Models.beacons

@{
    ViewBag.Title = "Редактирование бикона";
}

    <h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.beaconID)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uuid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uuid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uuid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.minor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.minor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.major, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.major, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.major, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.batteryLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.batteryLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.batteryLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nodeID, "ID ноды", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nodeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nodeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку биконов", "Index")
</div>

Indoor_app/Views/beacons/Index.cshtml
@model IEnumerable<Indoor_app.Models.beacons>

@{
    ViewBag.Title = "Список биконов";
}

<h2>Список биконов</h2>

@if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
{
    <p>
        @Html.ActionLink("Добавить бикон", "Create")
    </p>
}

<table class="table table-hover">
    <tr>
        <th>
            @Html.ActionLink("ID бикона", "Index", new { sortOrder = ViewBag.IdSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.uuid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.minor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.major)
        </th>
        <th>
            @Html.ActionLink("Уровень заряда", "Index", new { sortOrder = ViewBag.BatteryLevelSortParm })
        </th>

        <th>
            @Html.DisplayNameFor(model => model.language)
        </th>
        <th>
            @Html.ActionLink("ID ноды", "Index", new { sortOrder = ViewBag.NodeIdSortParm })
        </th>
        <th>
            @Html.ActionLink("Номер этажа", "Index", new { sortOrder = ViewBag.MapLevelSortParm })
        </th>
        <th>
            @Html.ActionLink("Название здания ENG", "Index", new { sortOrder = ViewBag.BuildingSortParm })
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "beacons", new { id = item.beaconID }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.beaconID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.uuid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.minor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.major)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.batteryLevel)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.language)
                </td>
                <td>
                    <a href="@Url.Action("Details", "nodes", new { id = item.nodes.nodeID })" rel="noopener noreferrer" target="_blank">
                        @Html.DisplayFor(modelItem => item.nodes.nodeID)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "floors", new { id = item.nodes.floors.floorID })" rel="noopener noreferrer" target="_blank">
                        @Html.DisplayFor(modelItem => item.nodes.floors.mapLevel)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "buildings", new { id = item.nodes.floors.buildings.buildingID })" rel="noopener noreferrer" target="_blank">
                        @Html.DisplayFor(modelItem => item.nodes.floors.buildings.buildingName)
                    </a>
                </td>
                @if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
                {
                    <td>
                        <a href="@Url.Action("Details", "beacons", new { id = item.beaconID })" class="btn btn-success">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "beacons", new { id = item.beaconID })" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </td>
                    <td>
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Вы точно хотите удалить бикон c ID @item.beaconID?')">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </td>
                }

            </tr>
        }
    }

</table>