Indoor_app/Controllers/ModelControllers/nodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Indoor_app.Models;

namespace Indoor_app.Controllers
{
    [Authorize(Users = AccessLevelUsers.Users)]
    public class nodesController : Controller
    {
        private BeaconDBEntities db = new BeaconDBEntities();

        // GET: nodes
        [AllowAnonymous]
        public ActionResult Index(string sortOrder)
        {
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.RoomTypeSortParm = sortOrder == "roomType" ? "roomType_desc" : "roomType";
            ViewBag.RoomNumSortParm = sortOrder == "roomNum" ? "roomNum_desc" : "roomNum";
            ViewBag.TypeSortParm = sortOrder == "type" ? "type_desc" : "type";
            ViewBag.FloorIdSortParm = sortOrder == "floorID" ? "floorID_desc" : "floorID";
            ViewBag.MapLevelSortParm = sortOrder == "mapLevel" ? "mapLevel_desc" : "mapLevel";
            ViewBag.BuildingSortParm = sortOrder == "building" ? "building_desc" : "building";

            var nodes = from s in db.nodes select s;
            switch (sortOrder)
            {
                case "roomType":
                    nodes = nodes.OrderBy(s => s.roomType);
                    break;
                case "roomType_desc":
                    nodes = nodes.OrderByDescending(s => s.roomType);
                    break;
                case "roomNum":
                    nodes = nodes.OrderBy(s => s.roomNum);
                    break;
                case "roomNum_desc":
                    nodes = nodes.OrderByDescending(s => s.roomNum);
                    break;
                case "type":
                    nodes = nodes.OrderBy(s => s.type);
                    break;
                case "type_desc":
                    nodes = nodes.OrderByDescending(s => s.type);
                    break;
                case "floorID":
                    nodes = nodes.OrderBy(s => s.floors.floorID);
                    break;
                case "floorID_desc":
                    nodes = nodes.OrderByDescending(s => s.floors.floorID);
                    break;
                case "mapLevel":
                    nodes = nodes.OrderBy(s => s.floors.mapLevel);
                    break;
                case "mapLevel_desc":
                    nodes = nodes.OrderByDescending(s => s.floors.mapLevel);
                    break;
                case "building":
                    nodes = nodes.OrderBy(s => s.floors.buildings.buildingName);
                    break;
                case "building_desc":
                    nodes = nodes.OrderByDescending(s => s.floors.buildings.buildingName);
                    break;
                case "id_desc":
                    nodes = nodes.OrderByDescending(s => s.nodeID);
                    break;
                default:
                    nodes = nodes.OrderBy(s => s.nodeID);
                    break;
            }
            return View(nodes.ToList());

            //var nodes = db.nodes.Include(n => n.floors);
            //return View(nodes.ToList());
        }

        // GET: nodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nodes nodes = db.nodes.Find(id);
            if (nodes == null)
            {
                return HttpNotFound();
            }
            return View(nodes);
        }

        // GET: nodes/Create
        public ActionResult Create()
        {
            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID");
            return View();
        }

        // POST: nodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nodeID,description,roomType,roomNum,coordX,coordY,type,floorID")] nodes nodes)
        {
            if (ModelState.IsValid)
            {
                db.nodes.Add(nodes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID", nodes.floorID);
            return View(nodes);
        }

        // GET: nodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nodes nodes = db.nodes.Find(id);

            if (nodes == null)
            {
                return HttpNotFound();
            }
            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID", nodes.floorID);
            
            
            //ViewBag.buildingNameRUS = new SelectList(db.buildings, "buildingNameRU", "buildingNameRU", nodes.floors.buildings.buildingNameRu);
            return View(nodes);
        }

        // POST: nodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nodeID,description,roomType,roomNum,coordX,coordY,type,floorID")] nodes nodes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nodes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.floorID = new SelectList(db.floors, "floorID", "floorID", nodes.floorID);

            //мультиселект?
            //@Html.DropDownList("buildingNameRUS", null, htmlAttributes: new { @class = "form-control" })
            //ViewBag.buildingNameRUS = new SelectList(db.buildings, "floorID", "buildingNameRU", nodes.floors.buildings.buildingNameRu);

            return View(nodes);
        }

        // GET: nodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nodes nodes = db.nodes.Find(id);
            if (nodes == null)
            {
                return HttpNotFound();
            }
            return View(nodes);
        }

        // POST: nodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            nodes nodes = db.nodes.Find(id);
            db.nodes.Remove(nodes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Indoor_app/Controllers/ModelControllers/wifisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Indoor_app.Models;

namespace Indoor_app.Controllers
{
    [Authorize(Users = AccessLevelUsers.Users)]
    public class wifisController : Controller
    {
        private BeaconDBEntities db = new BeaconDBEntities();

        // GET: wifis
        [AllowAnonymous]
        public ActionResult Index(string sortOrder)
        {
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.PowerSortParm = sortOrder == "power" ? "power_desc" : "power";
            ViewBag.NodeIdSortParm = sortOrder == "nodeID" ? "nodeID_desc" : "nodeID";
            ViewBag.MapLevelSortParm = sortOrder == "mapLevel" ? "mapLevel_desc" : "mapLevel";
            ViewBag.BuildingSortParm = sortOrder == "building" ? "building_desc" : "building";

            var wifiSpots = from s in db.wifi select s;
            switch (sortOrder)
            {
                case "power":
                    wifiSpots = wifiSpots.OrderBy(s => s.power);
                    break;
                case "power_desc":
                    wifiSpots = wifiSpots.OrderByDescending(s => s.power);
                    break;
                case "nodeID":
                    wifiSpots = wifiSpots.OrderBy(s => s.nodes.nodeID);
                    break;
                case "nodeID_desc":
                    wifiSpots = wifiSpots.OrderByDescending(s => s.nodes.nodeID);
                    break;
                case "mapLevel":
                    wifiSpots = wifiSpots.OrderBy(s => s.nodes.floors.mapLevel);
                    break;
                case "mapLevel_desc":
                    wifiSpots = wifiSpots.OrderByDescending(s => s.nodes.floors.mapLevel);
                    break;
                case "building":
                    wifiSpots = wifiSpots.OrderBy(s => s.nodes.floors.buildings.buildingName);
                    break;
                case "building_desc":
                    wifiSpots = wifiSpots.OrderByDescending(s => s.nodes.floors.buildings.buildingName);
                    break;
                case "id_desc":
                    wifiSpots = wifiSpots.OrderByDescending(s => s.wifiID);
                    break;
                default:
                    wifiSpots = wifiSpots.OrderBy(s => s.wifiID);
                    break;
            }
            return View(wifiSpots.ToList());
            //var wifi = db.wifi.Include(w => w.nodes);
            //return View(wifi.ToList());
        }

        // GET: wifis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            wifi wifi = db.wifi.Find(id);
            if (wifi == null)
            {
                return HttpNotFound();
            }
            return View(wifi);
        }

        // GET: wifis/Create
        public ActionResult Create()
        {
            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID");
            return View();
        }

        // POST: wifis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "wifiID,IP,SSID,power,nodeID")] wifi wifi)
        {
            if (ModelState.IsValid)
            {
                db.wifi.Add(wifi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID", wifi.nodeID);
            return View(wifi);
        }

        // GET: wifis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            wifi wifi = db.wifi.Find(id);
            if (wifi == null)
            {
                return HttpNotFound();
            }
            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID", wifi.nodeID);
            return View(wifi);
        }

        // POST: wifis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "wifiID,IP,SSID,power,nodeID")] wifi wifi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wifi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.nodeID = new SelectList(db.nodes, "nodeID", "nodeID", wifi.nodeID);
            return View(wifi);
        }

        // GET: wifis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            wifi wifi = db.wifi.Find(id);
            if (wifi == null)
            {
                return HttpNotFound();
            }
            return View(wifi);
        }

        // POST: wifis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            wifi wifi = db.wifi.Find(id);
            db.wifi.Remove(wifi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Indoor_app/Views/wifis/Create.cshtml
@model Indoor_app.Models.wifi

@{
    ViewBag.Title = "Добавление Wi-Fi точки";
}

<h2>Добавление</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.power, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.power, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.power, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nodeID, "ID ноды", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nodeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nodeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку Wi-Fi точек", "Index")
</div>

Indoor_app/Views/wifis/Delete.cshtml
@model Indoor_app.Models.wifi

@{
    ViewBag.Title = "Удаление Wi-Fi точки";
}

<h2>Удаление</h2>

<h3>Точно хотите удалить эту Wi-Fi точку?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.power)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.power)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nodes.nodeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nodes.nodeID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К списку Wi-Fi точек", "Index")
        </div>
    }
</div>

Indoor_app/Views/wifis/Details.cshtml
@model Indoor_app.Models.wifi

@{
    ViewBag.Title = "Описание Wi-Fi точки";
}

    <h2>Описание</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.power)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.power)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nodes.nodeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nodes.nodeID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактирование", "Edit", new { id = Model.wifiID }) |
    @Html.ActionLink("К списку Wi-Fi точек", "Index")
</p>

Indoor_app/Views/wifis/Edit.cshtml
@model Indoor_app.Models.wifi

@{
    ViewBag.Title = "Редактирование Wi-Fi точки";
}

    <h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.wifiID)

        <div class="form-group">
            @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.power, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.power, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.power, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nodeID, "ID ноды", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nodeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nodeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку Wi-Fi точек", "Index")
</div>

Indoor_app/Views/wifis/Index.cshtml
@model IEnumerable<Indoor_app.Models.wifi>

@{
    ViewBag.Title = "Список Wi-Fi точек";
}

<h2>Список Wi-Fi точек</h2>

@if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
{
    <p>
        @Html.ActionLink("Добавить Wi-Fi точку", "Create")
    </p>
}

<table class="table table-hover">
    <tr>
        <th>
            @Html.ActionLink("ID Wi-Fi точки", "Index", new { sortOrder = ViewBag.IdSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSID)
        </th>
        <th>
            @Html.ActionLink("Уровень сигнала", "Index", new { sortOrder = ViewBag.PowerSortParm })
        </th>
        <th>
            @Html.ActionLink("ID ноды", "Index", new { sortOrder = ViewBag.NodeIdSortParm })
        </th>
        <th>
            @Html.ActionLink("Номер этажа", "Index", new { sortOrder = ViewBag.MapLevelSortParm })
        </th>
        <th>
            @Html.ActionLink("Название здания ENG", "Index", new { sortOrder = ViewBag.BuildingSortParm })
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "wifis", new { id = item.wifiID }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.wifiID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SSID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.power)
                </td>
                <td>
                    <a href="@Url.Action("Details", "nodes", new { id = item.nodes.nodeID })" rel="noopener noreferrer" target="_blank">
                        @Html.DisplayFor(modelItem => item.nodes.nodeID)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "floors", new { id = item.nodes.floors.floorID })" rel="noopener noreferrer" target="_blank">
                        @Html.DisplayFor(modelItem => item.nodes.floors.mapLevel)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "buildings", new { id = item.nodes.floors.buildings.buildingID })" rel="noopener noreferrer" target="_blank">
                        @Html.DisplayFor(modelItem => item.nodes.floors.buildings.buildingName)
                    </a>
                </td>
                @if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
                {
                    <td>
                        <a href="@Url.Action("Details", "wifis", new { id = item.wifiID })" class="btn btn-success">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "wifis", new { id = item.wifiID })" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </td>
                    <td>
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Вы точно хотите удалить Wi-Fi точку c ID @item.wifiID?')">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </td>
                }
            </tr>
        }
    }

</table>