Indoor_app/Controllers/ModelControllers/floorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Indoor_app.Models;

namespace Indoor_app.Controllers
{
    [Authorize(Users = AccessLevelUsers.Users)]
    public class floorsController : Controller
    {
        private BeaconDBEntities db = new BeaconDBEntities();

        // GET: floors
        [AllowAnonymous]
        public ActionResult Index(string sortOrder)
        {
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.LevelSortParm = sortOrder == "Level" ? "level_desc" : "Level";
            ViewBag.BuildingSortParm = sortOrder == "building" ? "building_desc" : "building";


            var floors = from s in db.floors select s;
            switch (sortOrder)
            {
                case "Level":
                    floors = floors.OrderBy(s => s.mapLevel);
                    break;
                case "level_desc":
                    floors = floors.OrderByDescending(s => s.mapLevel);
                    break;
                case "building":
                    floors = floors.OrderBy(s => s.buildings.buildingName);
                    break;
                case "building_desc":
                    floors = floors.OrderByDescending(s => s.buildings.buildingName);
                    break;
                case "id_desc":
                    floors = floors.OrderByDescending(s => s.floorID);
                    break;
                default:
                    floors = floors.OrderBy(s => s.floorID);
                    break;
            }
            return View(floors.ToList());
        }

        // GET: floors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            floors floors = db.floors.Find(id);
            if (floors == null)
            {
                return HttpNotFound();
            }
            return View(floors);
        }

        // GET: floors/Create
        public ActionResult Create()
        {
            ViewBag.buildingID = new SelectList(db.buildings, "buildingID", "buildingName");
            return View();
        }

        // POST: floors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "floorID,description,directory,mapLevel,width,height,buildingID, imageFilePath")] floors floor)
        {
            if (ModelState.IsValid)
            {
                //old code
                /*buildings building = db.buildings.Where(b => b.buildingID == floor.buildingID).SingleOrDefault();
                
                string fileName = floor.mapLevel.ToString();
                string extension = Path.GetExtension(floor.imageFilePath.FileName);
                fileName = fileName + extension;

                string directoryName = building.buildingName + "\\";
                directoryName = Path.Combine(Server.MapPath("~/maps/"), directoryName);

                floor.directory = "~/maps/" + building.buildingName + "/" + fileName;

                fileName = Path.Combine(directoryName, fileName);

                if (!Directory.Exists(directoryName))
                {
                    Directory.CreateDirectory(directoryName);
                }

                floor.imageFilePath.SaveAs(fileName);
                db.floors.Add(floor);
                db.SaveChanges();

                return RedirectToAction("Index");*/

                buildings building = db.buildings.Where(b => b.buildingID == floor.buildingID).SingleOrDefault();

                //имя не порезанного файла карты
                string fileName = floor.mapLevel.ToString();
                string extension = Path.GetExtension(floor.imageFilePath.FileName);
                fileName = fileName + extension;

                //пути до картинки
                string directoryName = building.buildingName + "\\" + floor.mapLevel.ToString() + "\\";
                directoryName = Path.Combine(Server.MapPath("~/maps/"), directoryName);

                floor.directory = "~/maps/" + building.buildingName + "/" + floor.mapLevel.ToString() + "\\";

                fileName = Path.Combine(directoryName, fileName);

                if (!Directory.Exists(directoryName))
                {
                    Directory.CreateDirectory(directoryName);
                }

                floor.imageFilePath.SaveAs(fileName);
                db.floors.Add(floor);
                db.SaveChanges();

                var img = Image.FromFile(fileName);
                int map_def_size = 256;

                int xSize = ((int)Math.Ceiling((double)img.Width / map_def_size)); //* map_def_size;
                int ySize = ((int)Math.Ceiling((double)img.Height / map_def_size)); //* map_def_size;

                Size size = new Size(xSize, ySize);

                int tile = 256;

                for (int x = 0; x < size.Width; x++)
                {
                    for (int y = 0; y < size.Height; y++)
                    {
                        string outputFileName = Path.Combine(directoryName, string.Format("{0}-{1}.png", x, y));

                        Rectangle tileBounds = new Rectangle(x * tile, y * tile, tile, tile);
                        Bitmap target = new Bitmap(tile, tile);

                        using (Graphics graphics = Graphics.FromImage(target))
                        {
                            graphics.DrawImage(
                                img,
                                new Rectangle(0, 0, tile, tile),
                                tileBounds,
                                GraphicsUnit.Pixel);
                        }

                        target.Save(outputFileName, ImageFormat.Png);
                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.buildingID = new SelectList(db.buildings, "buildingID", "buildingName", floor.buildingID);
            return View(floor);
        }

        // GET: floors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            floors floors = db.floors.Find(id);
            if (floors == null)
            {
                return HttpNotFound();
            }
            ViewBag.buildingID = new SelectList(db.buildings, "buildingID", "buildingName", floors.buildingID);
            return View(floors);
        }

        // POST: floors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "floorID,description,directory,mapLevel,width,height,buildingID,imageFilePath")] floors floor)
        {
            if (ModelState.IsValid)
            {
                buildings building = db.buildings.Where(b => b.buildingID == floor.buildingID).SingleOrDefault();

                floors oldFloor = db.floors.AsNoTracking().Where(b => b.floorID == floor.floorID).SingleOrDefault();
                int oldMapLevel = oldFloor.mapLevel ?? 0;

                string oldFileName = building.buildingName + "/" + oldFloor.mapLevel.ToString() + Path.GetExtension(oldFloor.directory);
                string oldDirectoryName = Path.Combine(Server.MapPath("~/maps/"), oldFileName);

                db.Entry(floor).State = EntityState.Modified;

                //сначала проверяем загружали ли новую фотографию
                //если да, то удаляем старую и обновляем поле новой записью
                //если нет, то написано
                if (floor.imageFilePath != null)
                {
                    oldFileName = Path.Combine(Server.MapPath("~/maps/"), oldFileName);

                    if (System.IO.File.Exists(oldFileName))
                    {
                        System.IO.File.Delete(oldFileName);
                    }

                    string newFileName = floor.mapLevel.ToString() + Path.GetExtension(oldFloor.directory);

                    floor.directory = "~/maps/" + building.buildingName + "/" + newFileName;

                    newFileName = building.buildingName + "/" + newFileName;
                    newFileName = Path.Combine(Server.MapPath("~/maps/"), newFileName);
                    //newFileName = Path.Combine(oldDirectoryName, newFileName);

                    floor.imageFilePath.SaveAs(newFileName);
                }
                else
                {
                    //нужно чтобы когда не меняем картинку не записывалась пустое значение
                    //другой варик настроить для POST передачу старых данных картинки
                    db.Entry(floor).Property(x => x.directory).IsModified = false;
                }

                if (oldFloor.mapLevel != floor.mapLevel)
                {
                    if (floor.mapLevel != null && oldFloor.mapLevel != null)
                    {
                        string oldFile = building.buildingName + "/" + oldFloor.mapLevel + Path.GetExtension(oldFloor.directory);
                        string newFile = building.buildingName + "/" + floor.mapLevel + Path.GetExtension(oldFloor.directory);

                        floor.directory = "~/maps/" + building.buildingName + "/" + floor.mapLevel.ToString() + Path.GetExtension(oldFloor.directory);

Indoor_app/Views/floors/Create.cshtml
@model Indoor_app.Models.floors

@{
    ViewBag.Title = "Добавление этажа";
}

    <h2>Добавление</h2>

@using (Html.BeginForm("Create", "floors", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.directory, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="imageFilePath" required>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.mapLevel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mapLevel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mapLevel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.width, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.width, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.width, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.height, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.height, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.height, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.buildingID, "buildingID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("buildingID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.buildingID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Добавить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("К списку этажей", "Index")
</div>

Indoor_app/Views/floors/Delete.cshtml
@model Indoor_app.Models.floors

@{
    ViewBag.Title = "Удаление этажа";
}

    <h2>Удаление</h2>

<h3>Точно хотите удалить этот этаж?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.directory)
        </dt>

        <dd>
            @if (Model.directory != null)
            {
                <img src="@Url.Content(Model.directory)" width="250" height="250" multiple />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mapLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mapLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.buildings.buildingName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.buildings.buildingName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К списку этажей", "Index")
        </div>
    }
</div>

Indoor_app/Views/floors/Details.cshtml
@model Indoor_app.Models.floors

@{
    ViewBag.Title = "Описание этажа";
}

    <h2>Описание</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.directory)
        </dt>

        @if (Model.directory != null)
        {
            <dd>
                <img src="@Url.Content(Model.directory + Model.mapLevel.ToString() + Model.imageFilePath + ".png")" width="250" height="250" multiple />
            </dd>
        }

        @if (Model.directory == null)
        {
            <dd>
                <text>Не загружена</text>
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.mapLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mapLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.buildings.buildingName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.buildings.buildingName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактирование", "Edit", new { id = Model.floorID }) |
    @Html.ActionLink("К списку этажей", "Index")
</p>

Indoor_app/Views/floors/Edit.cshtml
@model Indoor_app.Models.floors

@{
    ViewBag.Title = "Редактирование этажа";
}

    <h2>Редактирование</h2>

@using (Html.BeginForm("Edit", "floors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.floorID)

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.directory, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (Model.directory != null)
            {
                <img src="@Url.Content(Model.directory)" width="250" height="250" multiple />
            }
            <input type="file" name="imageFilePath">
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.mapLevel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mapLevel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mapLevel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.width, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.width, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.width, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.height, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.height, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.height, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.buildingID, "Название здания ENG", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("buildingID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.buildingID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("К списку этажей", "Index")
</div>

Indoor_app/Views/floors/Index.cshtml
@model IEnumerable<Indoor_app.Models.floors>

@{
    ViewBag.Title = "Список этажей";
}

<h2>Список этажей</h2>

@if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
{
    <p>
        @Html.ActionLink("Добавить этаж", "Create")
    </p>
}

<table class="table table-hover">
    <tr>
        <th>
            @Html.ActionLink("ID этажа", "Index", new { sortOrder = ViewBag.IdSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.directory)
        </th>
        <th>
            @Html.ActionLink("Номер этажа", "Index", new { sortOrder = ViewBag.LevelSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.height)
        </th>
        <th>
            @Html.ActionLink("Название здания ENG", "Index", new { sortOrder = ViewBag.BuildingSortParm })
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "floors", new { id = item.floorID }))
        {
<tr>
    <th>
        @Html.DisplayFor(model => item.floorID)
    </th>
    <td>
        @Html.DisplayFor(modelItem => item.description)
    </td>
    <td>
        @if (item.directory == null)
        {
            <text> Не загружен </text>
        }
        else
        {
            <text> Загружен </text>
        }
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.mapLevel)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.width)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.height)
    </td>
    <td>
        <a href="@Url.Action("Details", "buildings", new { id = item.buildingID })"  rel="noopener noreferrer" target="_blank">
            @Html.DisplayFor(modelItem => item.buildings.buildingName)
        </a>
    </td>
    @if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
    {
        <td>
            <a href="@Url.Action("Details", "floors", new { id = item.floorID })" class="btn btn-success">
                <span class="glyphicon glyphicon-search"></span>
            </a>
        </td>
        @*<td>
            <a href="@Url.Action("Edit", "floors", new { id = item.floorID })" class="btn btn-warning">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
        </td>*@
        <td>
            @Html.AntiForgeryToken()
            <button type="submit" class="btn btn-danger" onclick="return confirm('Вы точно хотите удалить этаж c ID @item.floorID?')">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </td>
    }


</tr>
        }
    }

</table>