Indoor_app/Controllers/ModelControllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Indoor_app.Controllers
{
    [Authorize]
    public class InfoController : Controller
    {
        // GET: Info
        public ActionResult Index()
        {
            return View();
        }
    }
}

Indoor_app/Controllers/mapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Mvc;
using Indoor_app.Models;
using Indoor_app.Models.DTO;

namespace Indoor_app.Controllers
{
    [System.Web.Mvc.Authorize]
    public class mapController : Controller
    {
        private BeaconDBEntities db = new BeaconDBEntities();

        // GET: map
        public async Task<ActionResult> Index()
        {
            var buildings = await db.buildings.Include(b => b.floors).Select(b =>
                new buildingDetailsDTO()
                {
                    buildingID = b.buildingID,
                    buildingName = b.buildingName,
                    buildingNameRu = b.buildingNameRu,
                    matrixFile = b.matrixFile,
                    floors = b.floors.Select(floor => new floorDTO()
                    {
                        floorID = floor.floorID,
                        mapLevel = floor.mapLevel ?? 0,
                        buildingID = floor.buildingID ?? 0
                    }).ToList(),
                }).ToListAsync();


            var view = new MapViewModel()
            {
                BuildingId = buildings.FirstOrDefault().buildingID,
                Buildings = buildings,
                Floors = new List<floorDTO>()
            };

            return View(view);
        }

        [System.Web.Mvc.HttpPost]
        public async Task<ActionResult> Index(int buildingId)
        {
            var buildings = await db.buildings.Include(b => b.floors).Select(b =>
                new buildingDetailsDTO()
                {
                    buildingID = b.buildingID,
                    buildingName = b.buildingName,
                    buildingNameRu = b.buildingNameRu,
                    matrixFile = b.matrixFile,
                    floors = b.floors.Select(floor => new floorDTO()
                    {
                        floorID = floor.floorID,
                        mapLevel = floor.mapLevel ?? 0,
                        buildingID = floor.buildingID ?? 0
                    }).ToList(),
                }).ToListAsync();

            var floors = buildings.Where(x => x.buildingID == buildingId).Select(x => x.floors).FirstOrDefault();

            var view = new MapViewModel()
            {
                BuildingId = buildingId,
                Buildings = buildings,
                Floors = floors
            };

            return View(view);
        }
    }

    public class MapViewModel
    {
        public int BuildingId { get; set; }
        public List<buildingDetailsDTO> Buildings { get; set; }
        public List<floorDTO> Floors { get; set; }
    }
}

Indoor_app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | МИЭМ.Навигация</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @RenderSection("AddToHead", false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Request.IsAuthenticated)
                {
                    <a href="/info/index" class="navbar-brand"> <img src="~/Content/images/logo.png" alt="Company logo" width="50" height="50" /></a>
                }
                else
                {
                    <a href="/Account/login" class="navbar-brand"> <img src="~/Content/images/logo.png" alt="Company logo" width="50" height="50" /></a>

                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Информация", "Index", "Info")</li>
                        if (Indoor_app.Models.AccessLevelUsers.Users.Contains(User.Identity.Name))
                        {
                            <li>@Html.ActionLink("Редактор", "Index", "map")</li>
                        }
                        <li><a href="https://documenter.getpostman.com/view/10122624/SzKVRJ2L?version=latest" rel="noopener noreferrer" target="_blank">Документация по API</a></li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer id="footer">
            <hr />
            <text class="pull-left">МИЭМ.Навигация &copy; 2019 - @DateTime.Now.Year</text>
            <text><a href="https://indoor.moscowlab.info/" class="pull-right" rel="noopener noreferrer" target="_blank">О проекте</a></text>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>